//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaProdutosEletronicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Categorias
    {
        public int ID_Categoria { get; set; }
        public string Categoria { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
