//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaProdutosEletronicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Estoque
    {
        public int ID_Produto { get; set; }
        public string NomeProduto { get; set; }
        public Nullable<int> ID_Categoria { get; set; }
        public string Descricao { get; set; }
        public string Preco { get; set; }
        public string Fabricante { get; set; }
        public string DataDeFabricacao { get; set; }
        public string Processador { get; set; }
        public string Memoria { get; set; }
        public string Armazenamento { get; set; }
        public string Resolucao { get; set; }
        public string Tensao { get; set; }
        public string Dimensoes { get; set; }
        public string Peso { get; set; }
        public byte[] Imagem { get; set; }
        public string Status { get; set; }
        public Nullable<int> Deleted { get; set; }
        public string ID_Modelo { get; set; }
    }
}
